# action.yml
name: 'Build Skylark Pro app'
description: 'Builds an .sqfs file that can be uploaded to A Skyalrk Pro device'
inputs:
  app_name:
    description: 'What is the name of the app?'
    required: true
    default: 'unamed-app'
  rootfs:
    description: 'rootfs directory'
    required: true
    default: 'rootfs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app_name }}
    - ${{ inputs.rootfs }}
